### ISSUE TITLE
Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by Spidermain50** [g0t4/webpack-stats-graph#2]
I generated the stats.json file just fine. When I go to run the webpack-stats-graph command, I get the following result... 

Reading stats from stats.json
module.js:663
    throw err;
    ^

SyntaxError: C:\Users\<user>\Source\Repos\webpack\optimizing-web-apps-webpack\stats.json: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:660:27)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\webpack-stats-graph\index.js:120:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)

**Comment by GitNothing** [comment]
I got the exact same error from a simple test project. No � in my json file. Webpack ran and works fine.

**Comment by g0t4** [comment]
Could you tell me a bit about your environment and example & steps to repo? Also post a stats.json file?

**Comment by PetrShypila** [comment]
Went into the same issue. Here is the input:
```
Petrs-MacBook-Pro:CarPool petr$ npx webpack-stats-graph
Reading stats from stats.json
/Users/petr/Development/CarPool/stats.json: Unexpected token B in JSON at position 0
```

In fact, I just had some additional output in my webpack config file which polluted the JSON
```
Building in undefined mode
{
  "errors": [],
  "warnings": [],
  "version": "3.5.5",
  "hash": "1780e43d8e03b12e5921",
  "time": 9318,
  "publicPath": "/",
  "assetsByChunkName": {
    "main": "bundle.js"
...
```

Obviously, removing `Building in undefined mode` solved the issue

**Comment by g0t4** [comment]
Ahh yes, any additional output in the stats.json is going to be problematic.

I'll throw in a warning to check for this

**Comment by gitMonks** [comment]
Hi, 
I am running into the same issue when using following command:
npx webpack --mode development --entry ./app/app.js --output ./dist/app.bundle.js --json > stats.json

Can someone please help! Thanks in advance.

Here are the contents of my stats.json:

C:\Users\imran.ali\projs\webpack-course\node_modules\webpack\bin\webpack.js
{
  "errors": [],
  "warnings": [],
  "version": "4.7.0",
  "hash": "df91f36c96b203616b9e",
  "time": 127,
  "builtAt": 1525776313679,
  "publicPath": "",
  "outputPath": "C:\\Users\\imran.ali\\projs\\webpack-course\\dist",
  "assetsByChunkName": {
    "null": "app.bundle.js"
  },
  "assets": [
    {
      "name": "app.bundle.js",
      "size": 4022,
      "chunks": [
        0
      ],
      "chunkNames": [
        "null"
      ],
      "emitted": true
    }
  ],
  "filteredAssets": 0,
  "entrypoints": {
    "null": {
      "chunks": [
        0
      ],
      "assets": [
        "app.bundle.js"
      ],
      "children": {},
      "childAssets": {}
    }
  },
  "namedChunkGroups": {
    "null": {
      "chunks": [
        0
      ],
      "assets": [
        "app.bundle.js"
      ],
      "children": {},
      "childAssets": {}
    }
  },
  "chunks": [
    {
      "id": 0,
      "rendered": true,
      "initial": true,
      "entry": true,
      "size": 959,
      "names": [
        "null"
      ],
      "files": [
        "app.bundle.js"
      ],
      "hash": "bcc50e6fc17636d14503",
      "siblings": [],
      "parents": [],
      "children": [],
      "childrenByOrder": {},
      "modules": [
        {
          "id": 0,
          "identifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
          "name": "./app/app.js",
          "index": 0,
          "index2": 1,
          "size": 92,
          "cacheable": true,
          "built": true,
          "optional": false,
          "prefetched": false,
          "chunks": [
            0
          ],
          "issuer": null,
          "issuerId": null,
          "issuerName": null,
          "issuerPath": null,
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "assets": [],
          "reasons": [
            {
              "moduleId": null,
              "moduleIdentifier": null,
              "module": null,
              "moduleName": null,
              "type": "single entry",
              "userRequest": "./app/app.js",
              "loc": "null"
            }
          ],
          "providedExports": [],
          "optimizationBailout": [],
          "depth": 0,
          "source": "import \"./klondike/scoring.js\";\n\nangular.module(\"solitaire\", [\"klondike\", \"ngDraggable\"]);\n\n"
        },
        {
          "id": 1,
          "identifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\klondike\\scoring.js",
          "name": "./app/klondike/scoring.js",
          "index": 1,
          "index2": 0,
          "size": 867,
          "cacheable": true,
          "built": true,
          "optional": false,
          "prefetched": false,
          "chunks": [
            0
          ],
          "issuer": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
          "issuerId": 0,
          "issuerName": "./app/app.js",
          "issuerPath": [
            {
              "id": 0,
              "identifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
              "name": "./app/app.js"
            }
          ],
          "failed": false,
          "errors": 0,
          "warnings": 0,
          "assets": [],
          "reasons": [
            {
              "moduleId": 0,
              "moduleIdentifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
              "module": "./app/app.js",
              "moduleName": "./app/app.js",
              "type": "harmony side effect evaluation",
              "userRequest": "./klondike/scoring.js",
              "loc": "1:0-31"
            }
          ],
          "providedExports": null,
          "optimizationBailout": [],
          "depth": 1,
          "source": "angular.module(\"klondike.scoring\", [])\n  .service(\"scoring\", [function Scoring() {\n    \"use strict\";\n\n    this.score = 0;\n\n    this.newGame = function () {\n      this.score = 0;\n    };\n    this.tableauCardTurnedUp = function () {\n      this.score += 5;\n    };\n    this.dropped = function (source, destionation) {\n      this.score += scoreForMoving(source, destionation) || 0;\n    };\n    this.wasteRecycled = function () {\n      this.score = Math.max(this.score - 100, 0);\n    };\n\n    function scoreForMoving(source, destionation) {\n      if (destionation.name === \"TableauPile\") {\n        if (source.name === \"FoundationPile\") {\n          return -15;\n        }\n        return 5;\n      }\n      if (destionation.name === \"FoundationPile\") {\n        if (source.name === \"TableauPile\" || source.name === \"WastePile\") {\n          return 10;\n        }\n      }\n    }\n  }]);\n"
        }
      ],
      "filteredModules": 0,
      "origins": [
        {
          "module": "",
          "moduleIdentifier": "",
          "moduleName": "",
          "loc": "null",
          "request": "./app/app.js",
          "reasons": []
        }
      ]
    }
  ],
  "modules": [
    {
      "id": 0,
      "identifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
      "name": "./app/app.js",
      "index": 0,
      "index2": 1,
      "size": 92,
      "cacheable": true,
      "built": true,
      "optional": false,
      "prefetched": false,
      "chunks": [
        0
      ],
      "issuer": null,
      "issuerId": null,
      "issuerName": null,
      "issuerPath": null,
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "assets": [],
      "reasons": [
        {
          "moduleId": null,
          "moduleIdentifier": null,
          "module": null,
          "moduleName": null,
          "type": "single entry",
          "userRequest": "./app/app.js",
          "loc": "null"
        }
      ],
      "providedExports": [],
      "optimizationBailout": [],
      "depth": 0,
      "source": "import \"./klondike/scoring.js\";\n\nangular.module(\"solitaire\", [\"klondike\", \"ngDraggable\"]);\n\n"
    },
    {
      "id": 1,
      "identifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\klondike\\scoring.js",
      "name": "./app/klondike/scoring.js",
      "index": 1,
      "index2": 0,
      "size": 867,
      "cacheable": true,
      "built": true,
      "optional": false,
      "prefetched": false,
      "chunks": [
        0
      ],
      "issuer": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
      "issuerId": 0,
      "issuerName": "./app/app.js",
      "issuerPath": [
        {
          "id": 0,
          "identifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
          "name": "./app/app.js"
        }
      ],
      "failed": false,
      "errors": 0,
      "warnings": 0,
      "assets": [],
      "reasons": [
        {
          "moduleId": 0,
          "moduleIdentifier": "C:\\Users\\imran.ali\\projs\\webpack-course\\app\\app.js",
          "module": "./app/app.js",
          "moduleName": "./app/app.js",
          "type": "harmony side effect evaluation",
          "userRequest": "./klondike/scoring.js",
          "loc": "1:0-31"
        }
      ],
      "providedExports": null,
      "optimizationBailout": [],
      "depth": 1,
      "source": "angular.module(\"klondike.scoring\", [])\n  .service(\"scoring\", [function Scoring() {\n    \"use strict\";\n\n    this.score = 0;\n\n    this.newGame = function () {\n      this.score = 0;\n    };\n    this.tableauCardTurnedUp = function () {\n      this.score += 5;\n    };\n    this.dropped = function (source, destionation) {\n      this.score += scoreForMoving(source, destionation) || 0;\n    };\n    this.wasteRecycled = function () {\n      this.score = Math.max(this.score - 100, 0);\n    };\n\n    function scoreForMoving(source, destionation) {\n      if (destionation.name === \"TableauPile\") {\n        if (source.name === \"FoundationPile\") {\n          return -15;\n        }\n        return 5;\n      }\n      if (destionation.name === \"FoundationPile\") {\n        if (source.name === \"TableauPile\" || source.name === \"WastePile\") {\n          return 10;\n        }\n      }\n    }\n  }]);\n"
    }
  ],
  "filteredModules": 0,
  "children": []
}

**Comment by gitMonks** [comment]
By the way I have tried following:

- removed from the beginning of the file: C:\Users\imran.ali\projs\webpack-course\node_modules\webpack\bin\webpack.js
Then I get this error:

TypeError: Cannot read property 'toString' of null
    at issuers.m.reasons.map.d (C:\Users\imran.ali\AppData\Roaming\npm\node_modules\webpack-stats-graph\index.js:329:29)
    at Array.map (<anonymous>)
    at parseModule (C:\Users\imran.ali\AppData\Roaming\npm\node_modules\webpack-stats-graph\index.js:327:8)
    at Array.map (<anonymous>)
    at modulesByChunks.forEach.p (C:\Users\imran.ali\AppData\Roaming\npm\node_modules\webpack-stats-graph\index.js:410:8)
    at Array.forEach (<anonymous>)
    at buildGraph (C:\Users\imran.ali\AppData\Roaming\npm\node_modules\webpack-stats-graph\index.js:405:19)
    at Object.<anonymous> (C:\Users\imran.ali\AppData\Roaming\npm\node_modules\webpack-stats-graph\index.js:126:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

- build webpack in --mode none

**Comment by gitMonks** [comment]
I have found the solution here on this thread by the user @dvancuyk:

https://github.com/g0t4/webpack-stats-graph/issues/4

Thanks

**Comment by NigmaX** [comment]
if any one still gets the Unexpected token � in JSON at position 0, the solution is pretty simple.
1) make sure to remove the first line if it has a string like this: 
C:\Users\something\project\collstuffe\node_modules\webpack\bin\webpack.js
2) create a new stats.json file
3) copy the original stats.json and paste the content in the new stats.json

that should fix it, because when the file created, the UTF-8 is not supported for some reason.
Good luck
